#!/usr/bin/env bash
# Claude Code Status Line Script
# Displays: [hostname] 📁 directory | 🌿 branch-name
# Generated by Claude Code settings menu
#
# Contract:
# - Input: JSON via stdin with workspace.current_dir
# - Output: Single line to stdout with hostname, directory, git branch
# - Performance: <500ms execution time
# - Git operations: Timeout at 500ms to avoid hanging on slow filesystems

# Read JSON from stdin
INPUT=$(cat)

# Parse current directory from JSON
CURRENT_DIR=$(echo "$INPUT" | jq -r '.workspace.current_dir // ""' 2>/dev/null)
if [ -z "$CURRENT_DIR" ]; then
    # Fallback to PWD if JSON parsing fails
    CURRENT_DIR="$PWD"
fi

# Get hostname (try multiple methods)
HOSTNAME=$(hostname 2>/dev/null || cat /etc/hostname 2>/dev/null || echo "unknown")

# Get directory basename
DIR_NAME=$(basename "$CURRENT_DIR")

# Check for git branch (with timeout to prevent hanging)
GIT_BRANCH=""
if [ -d "$CURRENT_DIR" ]; then
    cd "$CURRENT_DIR" 2>/dev/null || true
    if timeout 0.5 git rev-parse --git-dir > /dev/null 2>&1; then
        # Try to get current branch name
        BRANCH=$(timeout 0.5 git branch --show-current 2>/dev/null || echo "")
        if [ -n "$BRANCH" ]; then
            GIT_BRANCH=" | \033[32m🌿 $BRANCH\033[0m"
        else
            # Detached HEAD - show short commit hash
            COMMIT=$(timeout 0.5 git rev-parse --short=7 HEAD 2>/dev/null || echo "")
            if [ -n "$COMMIT" ]; then
                GIT_BRANCH=" | \033[32m🌿 $COMMIT\033[0m"
            fi
        fi
    fi
fi

# Output formatted status line with ANSI colors
echo -e "\033[36m[$HOSTNAME]\033[0m 📁 $DIR_NAME$GIT_BRANCH"

# Always exit 0
exit 0
